name: LiftPlugin
main: no.atc.floyd.bukkit.lift.LiftPlugin
version: 0.11
website: http://minecraft.atc.no/plugins
author: FloydATC
description: >
        Stateless Lift plugin using signs and buttons
commands:
